server:
  port: 8080
  tomcat:
    relaxed-host-validation: true

spring:
  application:
    name: janus-gateway

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

# Expose all actuator health endpoints for Nginx upstream checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# Custom Janus config
janus:
  rules:
    directory: src/main/resources/rules